### ISSUE TITLE
numpy

### ISSUE THREAD

**Issue by Pilotix01** [patientx/ComfyUI-Zluda#15]
okay , i am fiddling around with this install here... numpy 
the whole install package is somehow f'd up

OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
[Impact Pack] EXECUTE: ['I:\\ai3\\ComfyUI-Zluda\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'opencv-python-headless'] in 'None'
### ComfyUI-Impact-Pack: Check basic models
Downloading https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth to I:\ai3\ComfyUI-Zluda\models\sams\sam_vit_b_01ec64.pth
100%|███████████████████████████████████████████████████████████████| 375042383/375042383 [00:40<00:00, 9331474.87it/s]
### ComfyUI-Impact-Pack: onnx model directory created (I:\ai3\ComfyUI-Zluda\models\onnx)
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['I:\\ai3\\ComfyUI-Zluda\\venv\\Scripts\\python.exe', 'install.py'] in 'I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
[Impact Pack] EXECUTE: ['I:\\ai3\\ComfyUI-Zluda\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'opencv-python'] in 'None'
[Impact Pack] EXECUTE: ['I:\\ai3\\ComfyUI-Zluda\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-U', 'opencv-python-headless'] in 'None'
### ComfyUI-Impact-Pack: Check basic models
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "I:\ai3\ComfyUI-Zluda\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
  File "I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in <module>
    import impact.core as core
  File "I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 10, in <module>
    from impact.utils import *
  File "I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 3, in <module>
    import cv2
  File "I:\ai3\ComfyUI-Zluda\venv\lib\site-packages\cv2\__init__.py", line 12, in <module>
    import numpy.core.multiarray
  File "I:\ai3\ComfyUI-Zluda\venv\lib\site-packages\numpy\core\multiarray.py", line 16, in <module>
    from ._multiarray_umath import (
ImportError: cannot import name 'fastCopyAndTranspose' from 'numpy.core._multiarray_umath' (I:\ai3\ComfyUI-Zluda\venv\lib\site-packages\numpy\core\_multiarray_umath.py)

**Comment by Pilotix01** [comment]
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: I:\ai3\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
I:\ai3\ComfyUI-Zluda\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)

**Comment by patientx** [comment]
You successfully installed numpy , after all , right ?

This part is normal : Ignore that.

`I:\ai3\ComfyUI-Zluda\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)`

And since this is the first generation zluda creates a database so you have to wait about 10-20 minutes. Let it finish the first time fully. After that it would be normal speed.

**Comment by tdm1000** [comment]
I've been having this issue when saving the output image. Numpy is definitely installed. Apologies if there was something obvious that I missed.
![image_2024-06-18_141924940](https://github.com/patientx/ComfyUI-Zluda/assets/42181814/fd84aaa2-66ed-4ac1-93da-fb51e5f2b288)

**Comment by Pilotix01** [comment]
somehow it runs now... idk what i did. but it runs so revert any changes. i installed this shitter 8 times today
