### ISSUE TITLE
nvcuda entry point issue after successful install

### ISSUE THREAD

**Issue by Foundit3923** [patientx/ComfyUI-Zluda#34]
### Your question

Issue:
![image](https://github.com/user-attachments/assets/b22cdc9a-719a-48cb-8d36-54f1b8c6a5b9)

Computer:
OS: Windows 10
CPU: Ryzen 5 3600
GPU: Vega 64
RAM: 32 GB DDR4

Steps to replicate:
Install dependencies as per instructions
Follow install instructions
Encounter Error
Run patchzluda
Encounter the same Error

I've attached the install log.

### Logs

```powershell
-------------------------------------------------------------
******************* COMFYUI-ZLUDA INSTALL *******************
-------------------------------------------------------------

 ::  15:46:11  ::  - Setting up the virtual enviroment
 ::  15:46:20  ::  - Virtual enviroment activation
 ::  15:46:20  ::  - Updating the pip package

 ::  15:46:26  ::  Beginning installation ...

 ::  15:46:26  ::  - Installing required packages
 ::  15:48:44  ::  - Installing torch for AMD GPUs (First file is 2.7 GB, please be patient)
 ::  15:51:17  ::  - Installing onnxruntime (required by some nodes)
 ::  15:51:26  ::  - (temporary numpy fix)

 ::  15:51:37  ::  Custom node(s) installation ...

 ::  15:51:37  ::  - Installing Comfyui Manager
 ::  15:51:39  ::  - Installing ComfyUI-deepcache
 ::  15:51:40  ::  - Installing ComfyUI-Impact-Pack

 ::  15:51:44  ::  - Patching ZLUDA (Zluda 3.8.4 for HIP SDK 5.7)
 ::  15:51:45  ::  - ZLUDA is patched.

.....................................................
*** Installation is completed in 00:05:33.61 .
*** You can use "comfyui.bat" to start the app later.
.....................................................
```

**Comment by patientx** [comment]
(First are make sure to use hip 5.7 not the latest one 6.x)
I am not sure but this is probably about the hip library not being the correct one. (once tried this with a 2200g so an apu, with a custom library made for it but it didn't work and was giving this kind of error)

**Comment by Foundit3923** [comment]
I made sure I installed 5.7.1

![image](https://github.com/user-attachments/assets/d04df817-2164-4506-a5d2-e3748a761c0a)

Can you expand on the gpu libraries?

I was previously using this with my vega 64, but had to wipe my drive and reinstall windows. So i know it's possible. just not sure what's wrong.

**Comment by Foundit3923** [comment]
I have solved that problem by updating my gpu drivers. Completely forgot that I needed to do that with a new install. I'm having a new issue where I'm unable to import the module 'segment_anything'. Do you want a new issue for that?

**Comment by patientx** [comment]
> I have solved that problem by updating my gpu drivers. Completely forgot that I needed to do that with a new install. I'm having a new issue where I'm unable to import the module 'segment_anything'. Do you want a new issue for that?

You can install it separately by activating the venv in comfyui directory.

> 
> ```
> .\venv\Scripts\activate
> pip install segment-anything
> deactivate
> ```

If there are other modules needed for that , try to install them this way as well.
