### ISSUE TITLE
Caffe2_nvrtc.dll error on install

### ISSUE THREAD

**Issue by rickguedes** [patientx/ComfyUI-Zluda#35]
### Expected Behavior

WebUI should run

### Actual Behavior

Returning the caffe2_nvrtc.dll error.

### Steps to Reproduce

Starting install.bat or comfyui.bat 

### Debug Logs

```powershell
*** Starting the Comfyui-ZLUDA for the first time, please be patient...

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-30 18:54:15.889996
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Users\dudur\Desktop\ComfyUI-Zluda\venv\Scripts\python.exe
** ComfyUI Path: C:\Users\dudur\Desktop\ComfyUI-Zluda
** Log path: C:\Users\dudur\Desktop\ComfyUI-Zluda\comfyui.log

Prestartup times for custom nodes:
  15.9 seconds: C:\Users\dudur\Desktop\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\dudur\Desktop\ComfyUI-Zluda\main.py", line 88, in <module>
    import comfy.utils
  File "C:\Users\dudur\Desktop\ComfyUI-Zluda\comfy\utils.py", line 20, in <module>
    import torch
  File "C:\Users\dudur\Desktop\ComfyUI-Zluda\venv\Lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\dudur\Desktop\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

### Other

- Using Python 3.11.9, had no windows store version, still tried deleting everything and reinstalling Python, no dice.
- I have C:\\Program Files\\AMD\\ROCm\\5.7\\ in both PATH and HIP_PATH, both in User and System variables. Checked the folder and and it exists with all the files, 5.7.1 is installed correctly.
- Installed the redist files too, no change
- Deleted venv folder and repo multiple times, rebooted, ran everything as Administrator and no change.

I have no idea what else to try. Even weirder, the "C:\Users\dudur\Desktop\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" file does exists in this path.
Oh, tried installing in a different folder to, no luck.

**Comment by rickguedes** [comment]
Tried updating GPU drivers, still no change, 24.10.1 and I have a 6900 XT

**Comment by Namadibus** [comment]
Same with my 7800xt.

**Comment by patientx** [comment]
Just thinking MAYBE IT IS MY SYSTEM , I installed windows 11 from scratch on a new hdd. Did everything step by step on the readme as if I am someone else doing it for the first time, and ... it just works.

**Comment by azamet90** [comment]
same here and last step on troubleshoot did also not solved my problem. i also added rocm in to path:
![image](https://github.com/user-attachments/assets/dfe01c50-25ca-4e3c-866b-c8825d4ab643)
![image](https://github.com/user-attachments/assets/abfe186b-00bb-46bd-a0ba-2cbccdd8f545)
to be sure i added them in to 2 place of paths...

how did you solved the problem?

**Comment by azamet90** [comment]
okay i fixed the problem with changing from powershell to default cmd

**Comment by soggywhale** [comment]
read the troubleshooting page it describes your problem and how to solve it

**Comment by Namadibus** [comment]
> read the troubleshooting page it describes your problem and how to solve it

I did everything as it says.

Nothing helped. And no, I didn't install Python from the Windows store.

**Comment by patientx** [comment]
> > read the troubleshooting page it describes your problem and how to solve it
> 
> I did everything as it says.
> 
> Nothing helped. And no, I didn't install Python from the Windows store.
> 
> SD.Next works for me with Zluda, though.

I also have both this and sdnext on my pc both AND running on different zluda versions actually. As I said above I installed one with a fresh system from the start as if I know nothing about this stuff and just typed it step by step , it works. So it is on your system sorry. There are tons of issues opened about this and I am suggesting everything there is found about this in the troubleshooting. 

Update your gpu driver, make sure there are no nvidia drivers left on the system (maybe from previous gpu's etc) , run the whole thing inside a command line not on powershell as suggested by someone above as their solution. Other than these and the ones on the troubleshooting part of readme I don't have any other solutions.

**Comment by Namadibus** [comment]
Fixed. 

Used SDK 5.7 and... Check your Paths. Both system and user. 

C:\Program Files\AMD\ROCm\5.7\bin (bin was my problem in user paths)
