### ISSUE TITLE
Crash without logs when loading lora

### ISSUE THREAD

**Issue by iNexusVitto** [patientx/ComfyUI-Zluda#40]
### Expected Behavior

When i first installed ComfyUI Zluda i was able to generate at least 1000x1000 images with normal VAE decode, 6.7GB checkpoint + 300MB Lora

### Actual Behavior

After updating i was forced to use VAE Decode tiled, with the latest update i can't load lora anymore, when loading new model at KSampler server crash without logs, in windows event it says phyton crashed withe exception code: 0xc0000005 and module error:\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\c10.dll. It seems an out of RAM crash but task manager says i still have 10GB 

### Steps to Reproduce

Start comfyUI, load checkpoint, load lora, generate, when in ksampler comfyui server stops, terminal says only "press a button to continue"

### Debug Logs

```powershell
[2024-11-13 22:02:21.870] Requested to load SDXL
[2024-11-13 22:02:21.870] Loading 1 new model
```

**Comment by patientx** [comment]
according to microsoft :

> Application Error 0xc0000005 (Access Violation) error is usually caused by your computer not being able to correctly process the files and settings required to run a particular program or installation. Despite the error showing when you try and use particular pieces of software, it has many different causes including faulty RAM problems, errors with the files of your PC and issues with the settings of your PC.

So your problem might not necessarily be about RAM. I would check the model and lora and maybe re-download them or try with other models & loras.

Another possible cause might be the visual c++ libraries, have you installed this , even if you install once again.

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by iNexusVitto** [comment]
Updating GPU driver seems to have solved the problem, but it could also have been the freeing up of space on the drive responsible for paging (now I have 10GB free).
