### ISSUE TITLE
caffe2 Error No Matter What I Do

### ISSUE THREAD

**Issue by Borkius** [patientx/ComfyUI-Zluda#44]
### Your question

I can see Hip on path, I've followed everything in the guide exactly, I don't have Python from Windows Store, but no matter what I do I always get 
"The specified module could not be found. Error loading "C:\Users\xxxx\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies."
No matter what.

I've tried both versions of Python in the guide and both give me this same problem.
I'm really confused on what's going on here.

I have a 7900xt and Windows 10.

**Comment by patientx** [comment]
I've seen it countless times and everytime there is something people are missing , so I am just going to paste the usual suspects here. Trust me, last time someone asked me this again, I installed windows 11 to another ssd just to test this fork and installed it going step by step, it is working.

Ensure your AMD GPU drivers are up to date
Ensure you don't have any left over nvidia drivers on your system. (You can use Display Driver Uninstaller to uninstall them)
Ensure that HIP SDK 5.7.1 is installed (and not 6.1.2)
Add these to your Environment Variables (if not already there):
HIP_PATH = C:\Program Files\AMD\ROCm\5.7\
HIP_PATH_57 = C:\Program Files\AMD\ROCm\5.7\
Add this to your System PATH environment variable:
C:\Program Files\AMD\ROCm\5.7\bin
Ensure you're not using Python install from the Windows Store. Download it from here.
Ensure you've installed optimised ROCm library files from ROCmLibs.

**Comment by f1am3d** [comment]
> HIP SDK 5.7.1

I have the same problem. With HIP SDK 5.7.1 and proper env vars.
