### ISSUE TITLE
Issues During Installation

### ISSUE THREAD

**Issue by AP-Sig** [patientx/ComfyUI-Zluda#48]
### Your question

I have followed all the steps in the Dependencies and Setup sections of the Readme, and I'm still having issues with installation. After running install.bat, this is the output I'm presented with in PowerShell:

![{9B7F6CF3-E52C-4916-B0A0-C2B81CCD083D}](https://github.com/user-attachments/assets/21dadd7a-43ae-4e6b-a3a8-f5e767b4ce8b)

I ended up manually downloading the release for Zluda from the GitHub here: https://github.com/lshqqytiger/ZLUDA/releases/download/rel.c0804ca624963aab420cb418412b1c7fbae3454b/ZLUDA-windows-rocm5-amd64.zip and extracted it to the ComfyUI-Zluda directory.

I copied the files from the Zluda directory into the correct locations exactly as they appear in the install.bat file:

> curl -s -L https://github.com/lshqqytiger/ZLUDA/releases/download/rel.c0804ca624963aab420cb418412b1c7fbae3454b/ZLUDA-windows-rocm5-amd64.zip > zluda.zip
> tar -xf zluda.zip
> del zluda.zip
> copy zluda\cublas.dll venv\Lib\site-packages\torch\lib\cublas64_11.dll /y >NUL
> copy zluda\cusparse.dll venv\Lib\site-packages\torch\lib\cusparse64_11.dll /y >NUL
> copy zluda\nvrtc.dll venv\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y >NUL

This fixed the issue I was seeing with the error "The system cannot find the path specified." from earlier, however, it presented the following issue when I tried to run comfyui.bat:

![{B5F36C9D-0555-480F-BCB8-AE2122C705C6}](https://github.com/user-attachments/assets/fd1a9331-31da-4e09-b9c6-e564b784067f)

I'm just not sure what to do at this point. I've tried to figure out solutions but searching hasn't provided any helpful suggestions.

**Comment by patientx** [comment]
First of all : If you have version 1803 or later of Windows 10, curl is installed by default. Windows 11 of course includes this as well. Your problem is you using powershell instead of commandline, just use commandline to install , every other problem would be solved.

**Comment by AP-Sig** [comment]
Man, I feel pretty dumb. Using command prompt instead of powershell worked fine and everything is loading correctly. Still glad I posted it, in case anyone in the future makes the same mistake. Thanks @patientx !
