### ISSUE TITLE
Can't Update to the Latest Version

### ISSUE THREAD

**Issue by trolly056** [patientx/ComfyUI-Zluda#51]
### Your question

Didn't know if i was supposed to make a bug report or not, honestly felt like all these "types" of issues just made things more confusing.  
![image](https://github.com/user-attachments/assets/bdf9f285-4071-4823-bf7d-9b8343ee042f)

*** Checking and updating to new version if possible
Updating 37d171a..819e120
error: Your local changes to the following files would be overwritten by merge:
        comfyui.bat
Please commit your changes or stash them before you merge.
Aborting

I don't understand why this is happening or how to fix it. I tried just copying ComfyUI-Zluda's original comfyui.bat but that doesn't work either. I don't understand how this file which is supposed to be customizable(it's a config file after all) would prevent an update. 
This is what's inside

@echo off

set PYTHON=%~dp0/venv/Scripts/python.exe
set GIT=
set VENV_DIR=./venv
set COMMANDLINE_ARGS=--lowvram --fp8_e4m3fn-unet --front-end-version Comfy-Org/ComfyUI_frontend@latest

set ZLUDA_COMGR_LOG_LEVEL=1

echo *** Checking and updating to new version if possible 
git pull
echo.
.\zluda\zluda.exe -- %PYTHON% main.py %COMMANDLINE_ARGS%
pause

I clicked on fix-update.bat but it just instantly closes( i don't think it's supposed to do that?), idk why this happened or what to do. Since it's specifically comfyui.bat which only exists for this fork, i assume this is the place to post an issue.

### Other
I only figured this out because i wanted to try out the new --use-sage-attention update. Which btw if you tried it out how good is it @patientx, because you are another lowvram boy like me, if you did try, did you like it?
_No response_

**Comment by patientx** [comment]
just delete the file. When updating it requires everything to be in the original form, if you want to use other commandline options rename it maybe or add them after updating once.

**Comment by trolly056** [comment]
But that's the comfyui.bat file, how am i supposed to start comfyui without it? that's my problem lol, unless i'm missing something

**Comment by patientx** [comment]
ok, then do this : delete the file. open the folder in commandline
 type : venv\scripts\activate (press enter)
type :  git pull (press enter)
this should update comfy and get the bat as well.

**Comment by trolly056** [comment]
Yup, that did it. Thanks.
