### ISSUE TITLE
supir cannot be executed normally

### ISSUE THREAD

**Issue by pinea00** [patientx/ComfyUI-Zluda#6]
https://github.com/kijai/ComfyUI-SUPIR/issues
I downloaded all the nodes and models that I should need. The execution process of CMD is all normal except for error messages, but the generated pictures are completely noisy.
Is there any way to fix it? Thanks
![ComfyUI_temp_idkmu_00001_](https://github.com/patientx/ComfyUI-Zluda/assets/57082420/404307af-4ac9-4ff0-b8d7-e89859b7cc2e)

**Comment by patientx** [comment]
I can't run it at all with my 8gb gpu sorry, can't test it myself.

**Comment by pinea00** [comment]
i'm 8G VRAM,too,someone said that supir need xformers to work.
Is real?
FP8 workflow in the file
[supisplitWF.json](https://github.com/patientx/ComfyUI-Zluda/files/15309033/supisplitWF.json)

**Comment by patientx** [comment]
"xformers is automatically detected and enabled if found, but it's not necessary, in some cases it can be a bit faster though"

Says on the github page. Tried it again. NOPE. It crashes my gpu (6600) even with smallest tile sizes, this is both with directml and zluda. Sorry, can't really test it. Maybe use another vae ?
