### ISSUE TITLE
Start.bat doesn't work

### ISSUE THREAD

**Issue by Dwanvea** [patientx/ComfyUI-Zluda#8]
If I use install.bat to launch web-ui, it works but that method reinstalls everything. I don't understand why start.bat won't work. It briefly opens a cmd window, then immediately disappears. No errors or anything. Do you know how I can fix this?

**Comment by patientx** [comment]
save these in a .bat file (for example comfy.bat) inside the folder and run it ::

`venv\scripts\activate`
`.\zluda\zluda.exe --python main.py`

There is nothing wrong with the default batch file.

**Comment by Dwanvea** [comment]
It's odd. I still face the same issue. Can I use this without zluda.exe? I feel like it's the culprit. My other zluda installations like (a1111 zluda) don't use the exe.

**Comment by Dwanvea** [comment]
s

**Comment by patientx** [comment]
> It's odd. I still face the same issue. Can I use this without zluda.exe? I feel like it's the culprit. My other zluda installations like (a1111 zluda) don't use the exe.

Of course, try it without zluda.

**Comment by patientx** [comment]
> Welp, I can't make it work. I tried running it trough cmd and it gives this error : " Error: OsError { function: "DetourCreateProcessWithDllsW", error_code: 193, message: "%1 is not a valid Win32 application." } "
> 
> My windows is 64 bit btw. Also comfy UI itself works fine when I open it trough install.bat. I don't understand what's causing this.
something is wrong with your python install, is it from windows store ? or this 

https://github.com/pytorch/pytorch/issues/27693

clean your python environment as shown there.

**Comment by Dwanvea** [comment]
No, my installation is from that link. Everything else works as well. I have multiple a1111 installations, onetrainer and stuff, everything works. Comfy works too but only from install.bat. I also tried re-installing pyhton. It still doesn't work. What a weird issue. I
