### ISSUE TITLE
caffe2_nvrtc.dll error back?

### ISSUE THREAD

**Issue by KrazyKZY** [patientx/ComfyUI-Zluda#9]
Update: MOVED directory to root of folder vs being in a sub-folder.  Works
----------------------

Fresh install - 7900 XTX  - ROCm 5.7
Second user also confirmed same error using fresh install.

Followed install steps exactly (tried python 3.10.9 and 3.11.9 from main python site - same error)
Paths - all entered in system variables

Tried patching - always get:

OSError: [WinError 126] The specified module could not be found. Error loading "E:\ComfyUI-Zluda\venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

**Comment by AlexDenthanor** [comment]
You closed this, but did you ever get it fixed?

**Comment by KrazyKZY** [comment]
Yes - redid the readme steps (adding path in both system and user variables
for ROCM 5.7)
Havent tried the new drop of ROCM
